### ISSUE TITLE
Error: EAFNOSUPPORT, Address family not supported by protocol

### ISSUE THREAD

**Issue by marioortizmanero** [agilob/nault-bin#2]
I've just updated my system and I'm getting this error when executing nault. The thing is that this happens even with the 1.9.2 PKGBUILD you made, which was working before. So an update of something else broke the package, apparently:

```
$ nault
A JavaScript error occurred in the main process
Uncaught Exception:
Error: EAFNOSUPPORT, Address family not supported by protocol
    at new Hci (/tmp/.mount_naulteCA1fs/resources/app.asar/node_modules/@abandonware/noble/lib/hci-socket/hci.js:74:18)
    at new NobleBindings (/tmp/.mount_naulteCA1fs/resources/app.asar/node_modules/@abandonware/noble/lib/hci-socket/bindings.js:25:15)
    at Object.<anonymous> (/tmp/.mount_naulteCA1fs/resources/app.asar/node_modules/@abandonware/noble/lib/hci-socket/bindings.js:546:18)
    at Module._compile (internal/modules/cjs/loader.js:967:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1004:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module._load (electron/js2c/asar.js:769:28)
    at Module.require (internal/modules/cjs/loader.js:852:19)
    at require (internal/modules/cjs/helpers.js:74:18)
```

Is this also happening to you?

**Comment by agilob** [comment]
No, I'm not having this problem with local wallet. I'll try later tomorrow if Ledger works.

**Comment by agilob** [comment]
I was checking this error code EAFNOSUPPORT, would that mean your system doesn't support ipv6 or your LAN has some mixed up address space? https://stackoverflow.com/questions/13452224/possible-causes-of-errno-97-aka-eafnosupport-aka-address-family-not-supported-by

https://www.gnu.org/software/libc/manual/html_node/Error-Codes.html

>Macro: int EAFNOSUPPORT
 “Address family not supported by protocol.” The address family specified for a socket is not supported; it is inconsistent with the protocol being used on the socket. See Sockets.

**Comment by marioortizmanero** [comment]
Huh nevermind after rebooting this was fixed for some reason. Sorry for the trouble, hopefully someone else will find this useful.

**Comment by agilob** [comment]
Have you upgraded kernel in the meantime?

**Comment by marioortizmanero** [comment]
Yeah it might have been the kernel. I get similar issues when I upgrade it without rebooting and try to use `docker` for example. But it works well after rebooting and I wouldn't count it as an issue. By the way, the PR for Nault has already been merged. We just have to wait for the release now.
